version: '3'
services:
  app:
    build: Flask
    restart: always
    volumes:
      - app:/app
    ports:     
      - "8000:8000"
  proxy:
    build: Nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  app:
